server:
  port: 8080
  servlet:
    context-path: /mariadb
spring:
  application:
    name: mariadb
  datasource:
    url: "jdbc:mysql://localhost:3306/maria_db"
    username: root
    password: vrain2403
jwt:
  signerKey: "f267b9918f787ae56447c9311ee8804e87cb512171fbe28a88ae4bd631ab3450"