server:
  port: 8080
  servlet:
    context-path: /mariadb
spring:
  application:
    name: mariadb
  datasource:
    primary:
      jdbc-url: ${PRIMARY_JDBC_URL}
      username: ${PRIMARY_JDBC_USERNAME}
      password: ${PRIMARY_JDBC_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: primary-pool
        maximum-pool-size: 5
        minimum-idle: 1
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
    secondary:
      jdbc-url: ${SECONDARY_JDBC_URL}
      username: ${SECONDARY_JDBC_USERNAME}
      password: ${SECONDARY_JDBC_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      hikari:
        pool-name: secondary-pool
        maximum-pool-size: 3
        minimum-idle: 1
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  base-url: ${APP_BASE_URL}
  frontend-url: ${FRONTEND_URL}
#  base-url: https://localhost:8080
#  frontend-url:
jwt:
  signerKey: "f267b9918f787ae56447c9311ee8804e87cb512171fbe28a88ae4bd631ab3450"
aws:
  s3:
    aws_access_key_id: ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    aws_session_token: ${AWS_SESSION_TOKEN}
    region: ${REGION}
    bucket-name: ${BUCKET_NAME}
backup:
  temp-dir: ./temp