server:
  port: 8080
  servlet:
    context-path: /mariadb
spring:
  application:
    name: mariadb
  datasource:
    primary:
      jdbc-url: "jdbc:mysql://database-1.cm8qkmiwivrg.us-east-1.rds.amazonaws.com:3306/coredb"
      username: admin
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: "jdbc:mariadb://database-2.cm8qkmiwivrg.us-east-1.rds.amazonaws.com:3306/"
      username: admin
      password: 12345678
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: publicmail711@gmail.com
    password: jfvx debw cobv grpi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  base-url: http://localhost:8080
  frontend-url: http://localhost:5173
jwt:
  signerKey: "f267b9918f787ae56447c9311ee8804e87cb512171fbe28a88ae4bd631ab3450"
aws:
  s3:
    
    region: us-east-1
    bucket-name: mariadb-bucket-123
backup:
  temp-dir: ./temp